apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-rc
      labeles:
        app: nginx
        ver: "1.0"
    spec:
      containers:
      - name: cont1
        image: nginx
        ports:
          - containerPort: 80