apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
      - name: cont1
        image: nginx
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80