apiVersion: v1
kind: ReplicationController
metadata:
  name: theDemoSet

spec:
  replicas: 5
  selector:
    env: test
    ver: "1.0"

  template:
    metadata:
      lables:
        env: test
        tech: nodejs
        ver: "1.0"
    
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80