apiVersion: v1
kind: ReplicationController
metadata:
  name: pvcomm-rc
spec:
  replicas: 5
  selector:
    org: pvc
  template:
    metadata:
      name: pvcomm
      labels:
        org: pvc
        ver: "1.0"
    spec:
      containers:
      - name: pvcomm_cont
        image: pekalaanil/pvcomm
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pvc_lb
spec:
  selector:
    org: pvc
  type: LoadBalancer
  ports:
  - port: 80